version: '3.7'

services:
  winn:
    # image: varunkamath14/winn:latest
    image: ghcr.io/varunkamath/winnbot:main
    container_name: winn
    network_mode: host
    platform: linux/amd64
    env_file:
      - env_vars
